# Generated by Django 5.2.17 on 2026-08-07 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('great', 'Energized / Great'), ('good', 'Calm / Focused'), ('neutral', 'Neutral / Okay'), ('anxious', 'Stressed / Anxious'), ('exhausted', 'Exhausted / Low')], max_length=20)),
                ('emoji', models.CharField(default='😌', max_length=10)),
                ('energy_level', models.IntegerField(default=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
