# Generated by Django 5.2.17 on 2026-08-10 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Mindfulness', 'Mindfulness'), ('Recovery', 'Recovery'), ('Physical', 'Physical'), ('Reflection', 'Reflection')], default='Mindfulness', max_length=20)),
                ('points', models.IntegerField(default=15)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_completed', '-id'],
            },
        ),
    ]
