# Generated by Django 5.2.17 on 2026-08-17 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('codex', 'Codex'), ('mindful_monsters', 'Mindful Monsters'), ('breathwork', 'Breathwork'), ('setback_reframer', 'Setback Reframer'), ('grit_garden', 'Grit Garden'), ('echoes_of_empathy', 'Echoes of Empathy'), ('counselor_hub', 'Counselor Hub'), ('transition_support', 'Transition Support'), ('locker_room_realities', 'Locker Room Realities'), ('reaction_zone', 'Reaction Zone'), ('integrity_crossroads', 'Integrity Crossroads'), ('self_talk_detective', 'Self-Talk Detective'), ('career_forge', 'Career Forge'), ('word_grid', 'Word Grid')], max_length=50)),
                ('required_xp', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WellnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wellness.wellnessmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='available', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_progress', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='wellness.wellnessmodule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_user_wellness_module')],
            },
        ),
        migrations.CreateModel(
            name='WellnessCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_completions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='wellness.wellnessmodule')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='wellness.wellnesssession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_wellness_completion')],
            },
        ),
    ]
