# Generated by Django 5.2.17 on 2026-08-17 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0008_counselor_counselorrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('guide', 'Guide'), ('download', 'Download')], default='article', max_length=30)),
                ('category', models.CharField(choices=[('career', 'Career'), ('education', 'Education'), ('skills', 'Skills'), ('life_after_sport', 'Life After Sport'), ('financial', 'Financial'), ('general', 'General')], default='general', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='transition_resources/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_resource_views', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='wellness.transitionresource')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'resource'), name='unique_transition_resource_view')],
            },
        ),
    ]
