# Generated by Django 5.2.17 on 2026-08-18 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0011_reactionprompt_reactiongamesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(default='Fair Play', max_length=100)),
                ('dilemma', models.TextField()),
                ('choices', models.JSONField(default=list, help_text='List of choices with text, score, and values_reflection')),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WordGridPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('title', models.CharField(default='Mental Grit Grid', max_length=150)),
                ('theme', models.CharField(default='Resilience & Focus', max_length=150)),
                ('grid', models.JSONField(default=list, help_text='2D array of letters representing the word search board')),
                ('target_words', models.JSONField(default=list, help_text='List of target words and hints')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-puzzle_date'],
            },
        ),
        migrations.AddField(
            model_name='wellnessmodule',
            name='icon',
            field=models.CharField(default='🧩', max_length=50),
        ),
        migrations.AlterField(
            model_name='wellnesscompletion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='wellness.wellnesssession'),
        ),
        migrations.AlterField(
            model_name='wellnessmodule',
            name='xp_reward',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('transferable_skills', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(default=list, help_text='List of milestones with title, deadline, status')),
                ('financial_goals', models.TextField(blank=True)),
                ('timeline_months', models.PositiveIntegerField(default=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegritySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.IntegerField(blank=True, null=True)),
                ('reflection', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wellness.integrityscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfTalkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_thought', models.TextField()),
                ('distortion_type', models.CharField(choices=[('all_or_nothing', 'All-or-Nothing Thinking'), ('catastrophizing', 'Catastrophizing'), ('mind_reading', 'Mind Reading'), ('overgeneralization', 'Overgeneralization'), ('should_statements', 'Should / Must Statements'), ('personalization', 'Personalization / Blaming'), ('other', 'General Unhelpful Thought')], default='other', max_length=50)),
                ('analysis', models.TextField(blank=True)),
                ('suggested_rewrite', models.TextField(blank=True)),
                ('actionable_tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_talk_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordGridScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_found', models.JSONField(default=list)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='wellness.wordgridpuzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_grid_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'time_taken_seconds'],
            },
        ),
    ]
