# Generated by Django 5.2.17 on 2026-08-19 14:24

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0012_integrityscenario_wordgridpuzzle_wellnessmodule_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellnesscompletion',
            options={'ordering': ['-completed_at']},
        ),
        migrations.RemoveConstraint(
            model_name='wellnesscompletion',
            name='unique_wellness_completion',
        ),
        migrations.AddField(
            model_name='wellnesscompletion',
            name='completion_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='wellnesscompletion',
            index=models.Index(fields=['user', 'completion_date'], name='wellness_we_user_id_0b6126_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnesscompletion',
            index=models.Index(fields=['user', 'module', 'completion_date'], name='wellness_we_user_id_15e224_idx'),
        ),
        migrations.AddConstraint(
            model_name='wellnesscompletion',
            constraint=models.UniqueConstraint(fields=('user', 'module', 'completion_date'), name='unique_daily_wellness_completion'),
        ),
    ]
