# Generated by Django 5.2.17 on 2026-08-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0013_alter_wellnesscompletion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellnesscompletion',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='wellnesscompletion',
            name='wellness_we_user_id_0b6126_idx',
        ),
        migrations.RemoveIndex(
            model_name='wellnesscompletion',
            name='wellness_we_user_id_15e224_idx',
        ),
        migrations.AlterField(
            model_name='wellnesscompletion',
            name='completion_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
