# Generated by Django 5.2.17 on 2026-08-10 08:17

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.profile_pic_path)),
                ('sport', models.CharField(blank=True, default='Football', max_length=100)),
                ('team', models.CharField(blank=True, default='University Varsity', max_length=100)),
                ('position', models.CharField(blank=True, default='Midfielder', max_length=100)),
                ('personal_goals', models.TextField(blank=True, default='Improve mental resilience and maintain daily focus targets.')),
                ('preferences', models.CharField(blank=True, default='Morning Workouts, Mindful Breathing', max_length=255)),
                ('email_notifications', models.BooleanField(default=True)),
                ('reminder_notifications', models.BooleanField(default=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
