# Generated by Django 5.2.17 on 2026-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('rain', 'Rain'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('wind', 'Wind'), ('meditation', 'Meditation')], max_length=30)),
                ('audio_file', models.FileField(upload_to='sound_therapy/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
