# Generated by Django 5.2.17 on 2026-08-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='requirements',
        ),
        migrations.AddField(
            model_name='badge',
            name='requirement_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('xp', 'XP'), ('streak', 'Streak'), ('goals', 'Goals'), ('mood', 'Mood'), ('activity', 'Activity')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('locked', 'Locked'), ('redeemed', 'Redeemed')], default='locked', max_length=20),
        ),
    ]
